---
title: "FIA Processing"
author: "Bryce DiNardo"
date: "2025-11-17"
output: html_document
params:
  species_code: 202
  years: !r c(2022)
  resolution: 0.01
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rFIA)
library(dplyr)
library(sf)
library(terra)
library(ggplot2)

```

## Load in FIA data


```{r}
or_fia <- readFIA("C:/Users/Bryce/OneDrive - University Of Oregon/FIA", nCores = 4)
or_fia <- clipFIA(or_fia)
```

Get data
```{r}
seedling_df <- seedling(
  db = or_fia,
  grpBy = c(PLT_CN, SPCD),
  bySpecies = TRUE,
  byPlot = TRUE,
  returnSpatial = TRUE,
  landType = "forest",
  method = "annual",
  treeDomain = SPCD == 202
)

```
```{r}
seedling_df <- seedling(
  db = or_fia,
  grpBy = c(PLT_CN, CONDID, SPCD),
  bySpecies = TRUE,
  byPlot = TRUE,
  returnSpatial = TRUE,
  landType = "forest",
  method = "annual",
  treeDomain = SPCD == 202
)

```
```{r}
rlang::last_trace()

```
```{r}
or_fia$SEEDLING %>% count(PLT_CN, SPCD) %>% filter(n > 1)

```
```{r}
?clipFIA
```
```{r}
findEVALID(
  db = or_fia,
  state = "Oregon",
  year = 2022
)

?findEVALID

findEVALID(
  db = or_fia,
  state = "Oregon",
  year = 2020,
  type = "CURR"
)

findEVALID(
  db = or_fia,
  state = "Oregon",
  year = 2022,
  type = "CURR"
)
```
Clippung data to just 2022 main tables
```{r}
or_fia_2022 <- clipFIA(
  db = or_fia,
  evalid = 412000,
  nCores = 4
)

test<-clipFIA(or_fia, mostRecent = TRUE, mask = NULL, matchEval = FALSE,
        evalid =FALSE , designCD = NULL, nCores = 4)
head(test)
unique(test$SEEDLING$INVYR)

head(or_fia)
```

```{r}
unique(or_fia$SEEDLING$INVYR)
```



```{r}

seedling_df <- seedling(
  db = or_fia_2022,
  grpBy = c(PLT_CN, CONDID, SPCD, INVYR),
  bySpecies = TRUE,
  byPlot = TRUE,
  returnSpatial = TRUE,
  landType = "forest",
  method = "annual",
  treeDomain = SPCD == 202
)

or_fia_2022$SEEDLING %>%
  count(PLT_CN, CONDID, SPCD) %>%
  filter(n > 1)

```
So have work around the
```{r}
seedling_raw <- seedling(
  db = or_fia_2022,
  byPlot = TRUE,
  bySpecies = TRUE,
  landType = "forest",
  method = "annual",
  treeDomain = SPCD == 202
)
head(seedling_raw)

unique(seedling_raw$YEAR)

```
Agh, pretyy much using the seedling function isn't going to work, there are multiple seed inputs uncer the same plot and I'm not how to deal with that issue, so I'm doing to dyplr it up in here and do this myself
